// Sample data for seeding the database
// Run this to populate your MongoDB with sample products

const sampleProducts = [
  {
    name: "Premium Casual T-Shirt",
    description: "High-quality cotton casual t-shirt perfect for everyday wear",
    price: 599,
    originalPrice: 1299,
    discount: 54,
    category: "Men",
    subcategory: "Tshirts",
    brand: "Nike",
    rating: 4.5,
    reviews: 1234,
    image: "https://via.placeholder.com/300x400?text=TShirt",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Blue", "Red"],
    stock: 150,
    tags: ["casual", "cotton", "comfortable"],
    isNew: true,
    isFeatured: true
  },
  {
    name: "Stylish Formal Shirt",
    description: "Elegant formal shirt for office and special occasions",
    price: 1299,
    originalPrice: 2499,
    discount: 48,
    category: "Men",
    subcategory: "Shirts",
    brand: "Adidas",
    rating: 4.3,
    reviews: 856,
    image: "https://via.placeholder.com/300x400?text=FormalShirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Light Blue", "Black"],
    stock: 89,
    tags: ["formal", "office", "elegant"],
    isNew: false,
    isFeatured: true
  },
  {
    name: "Comfortable Joggers",
    description: "Comfortable and stylish joggers for workout and casual wear",
    price: 899,
    originalPrice: 1799,
    discount: 50,
    category: "Men",
    subcategory: "Bottoms",
    brand: "Puma",
    rating: 4.7,
    reviews: 2145,
    image: "https://via.placeholder.com/300x400?text=Joggers",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Gray", "Navy"],
    stock: 200,
    tags: ["comfortable", "sports", "casual"],
    isNew: true,
    isFeatured: false
  },
  {
    name: "Classic Denim Jeans",
    description: "Timeless denim jeans that go with everything",
    price: 1399,
    originalPrice: 2799,
    discount: 50,
    category: "Men",
    subcategory: "Bottoms",
    brand: "Reebok",
    rating: 4.4,
    reviews: 1678,
    image: "https://via.placeholder.com/300x400?text=Jeans",
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Light Blue", "Dark Blue", "Black"],
    stock: 180,
    tags: ["denim", "classic", "versatile"],
    isNew: false,
    isFeatured: true
  },
  {
    name: "Women's Elegant Dress",
    description: "Beautiful and comfortable dress perfect for parties and occasions",
    price: 1799,
    originalPrice: 3499,
    discount: 49,
    category: "Women",
    subcategory: "Dresses",
    brand: "Nike",
    rating: 4.6,
    reviews: 945,
    image: "https://via.placeholder.com/300x400?text=WomensDress",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Red", "Black", "Navy"],
    stock: 95,
    tags: ["dress", "elegant", "party"],
    isNew: true,
    isFeatured: true
  },
  {
    name: "Athletic Sports Shoes",
    description: "Lightweight running shoes with excellent cushioning",
    price: 3999,
    originalPrice: 7999,
    discount: 50,
    category: "Footwear",
    subcategory: "Running Shoes",
    brand: "Adidas",
    rating: 4.8,
    reviews: 3456,
    image: "https://via.placeholder.com/300x400?text=SportShoes",
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Blue", "Red"],
    stock: 250,
    tags: ["sports", "shoes", "running"],
    isNew: false,
    isFeatured: true
  },
  {
    name: "Trendy Sunglasses",
    description: "Stylish UV protection sunglasses",
    price: 799,
    originalPrice: 1999,
    discount: 60,
    category: "Accessories",
    subcategory: "Eyewear",
    brand: "Puma",
    rating: 4.2,
    reviews: 567,
    image: "https://via.placeholder.com/300x400?text=Sunglasses",
    colors: ["Black", "Brown", "Gold"],
    stock: 120,
    tags: ["accessories", "sunglasses", "trendy"],
    isNew: true,
    isFeatured: false
  },
  {
    name: "Premium Leather Belt",
    description: "High-quality leather belt perfect for any occasion",
    price: 599,
    originalPrice: 1299,
    discount: 54,
    category: "Accessories",
    subcategory: "Belts",
    brand: "Reebok",
    rating: 4.4,
    reviews: 432,
    image: "https://via.placeholder.com/300x400?text=Belt",
    colors: ["Black", "Brown", "Tan"],
    stock: 160,
    tags: ["belt", "leather", "accessories"],
    isNew: false,
    isFeatured: false
  },
];

// Usage in MongoDB:
// 1. Connect to MongoDB
// 2. Use db.products.insertMany(sampleProducts)
// 3. Or integrate this into your seed script

module.exports = sampleProducts;
